Rebrush Elements in task subpages
openHPI/codeharbor pull request #1359
Opened 2024-04-16 21:30 UTC by zuhrasofyan

Apply styling for elements in task subpages:

### Elements re-brushed:
- Heading in view/edit task
- Star rating
- Numbering
- Dropdown button
- Dropdown comment
- Button group
- Form group

### Some clean-up:
- Replace inline styling of button icons with bootstrap's text-color classes
- Combining and small fixes on CSS
- Reducing the number of different color implemented in elements

### Implement similar element styling in other pages

### Here is the example of implemented element changes:
Before: 
<img width="1332" alt="Screenshot 2024-04-22 at 21 23 39" src="https://github.com/openHPI/codeharbor/assets/4398374/563e31d2-6a15-4524-8fd0-6e9a0af3fcd5">

![screencapture-codeharbor-openhpi-de-tasks-851-2024-04-16-23_26_59](https://github.com/openHPI/codeharbor/assets/4398374/d8047d9f-de4f-429e-98cc-8e6f0229e390)

After:
<img width="1349" alt="Screenshot 2024-04-22 at 21 13 59" src="https://github.com/openHPI/codeharbor/assets/4398374/6bb999da-b66f-4de4-92d9-cf0b16348e40">

![screencapture-127-0-0-1-7500-tasks-1-2024-04-16-23_26_09](https://github.com/openHPI/codeharbor/assets/4398374/a84cf1af-bba9-4881-ba9e-c4121cdb083e)

2024-05-09 20:25 UTC, kkoehn requested changes
Thanks for the design-rework. It looks really good and modern, but I'm sad to see most of the colors go.

Please have a look at the following points:
Your screenshot from the task-index looks good, but for me it looks like this (Firefox):
![image](https://github.com/openHPI/codeharbor/assets/24592181/856b6a24-2449-48bc-ad98-f988dbc064dd)
the vertical alignment of the rating-stars seems to be broken

For the group-show the (disabled) "Leave Group" also looks weird (at least the right border is missing but the white background also doesn't really fit)
![image](https://github.com/openHPI/codeharbor/assets/24592181/a46bfdc2-6319-4a96-af01-3c65384f6f11)

Task-view:
inconsistent font-weight for "Files:"
![image](https://github.com/openHPI/codeharbor/assets/24592181/8a0b4cc8-8ea1-4d57-822d-32b83f5e80c6)

2024-05-23 10:56 UTC, zuhrasofyan commented
For the cosmetics improvement you [suggested](https://github.com/openHPI/codeharbor/pull/1359#pullrequestreview-2048638364), unfortunately for the sake of simplification and not to have too many color variation, I tried to streamline and reduce too many color being used :/. Anyway, here are some improvement based on your review:
1) I adjusted the font size to fit the border alignment. Here the star-rating in firefox:
<img width="847" alt="Screenshot 2024-05-23 at 12 17 16" src="https://github.com/openHPI/codeharbor/assets/4398374/36dc23e5-9fd9-4f44-8dae-f7ca496f801e">

2) I've changed the color and border for disabled button in button group. Let me know if you have a better color match idea:
<img width="603" alt="Screenshot 2024-05-23 at 12 17 37" src="https://github.com/openHPI/codeharbor/assets/4398374/72c918d6-37f1-4132-b411-41bcac08992c">

3) Thanks for spotting that. It was the legacy code, and I forgot to adjust the similar styling.

2024-05-23 10:57 UTC, zuhrasofyan commented on app/views/account_links/show.html.slim
> +        = " #{AccountLink.model_name.human}: #{@account_link.name}"
Resolved

2024-05-23 10:58 UTC, zuhrasofyan commented on app/views/tasks/_tasks.html.slim
> +              /   = t("tasks.visibility.#{task.access_level}")
We don't. I will delete those lines

2024-05-23 18:47 UTC, kkoehn reviewed
Thanks for incorporating the suggestions.
I found a few more minor things. 

While testing the new design, I also stumbled over the following thing in `collection/show`:
![image](https://github.com/openHPI/codeharbor/assets/24592181/7a8123fc-0c74-454d-9dd4-84982c85d2d6)
While I don't think you touched it, could you still fix it?

2024-05-23 18:47 UTC, kkoehn commented on app/assets/stylesheets/exercises.css.scss
> +  color: $exercise-color;
since we moved from exercise to task `$task-color` would fit better, I think

2024-05-23 18:47 UTC, kkoehn commented on app/views/tasks/_tasks.html.slim
> +                - if task.access_level == 'public'
```suggestion
                - if task.access_level_public?
```

2024-05-26 10:26 UTC, MrSerth commented
The `Collections#show` route looks weird in German:

<img width="1319" alt="Bildschirmfoto 2024-05-26 um 12 24 15" src="https://github.com/openHPI/codeharbor/assets/7300329/06b7cd64-352a-4025-9dee-bca445e52a61">

First, the action buttons are really too long with non-unified line breaks (see the "Back" button: It's not centered as all other text). Then, there are some elements still using colors, whereas others lost it (check the "statistics" about members, invitations, the title, ...).

2024-05-29 10:07 UTC, MrSerth commented
Regarding the colors: I still feel that we should either go with some colored icons or none at all. What do you think about this mix?

![Bildschirmfoto 2024-05-29 um 12 06 47](https://github.com/openHPI/codeharbor/assets/7300329/c61e29c1-8429-4300-a988-573101ddf46c)

2024-05-29 10:11 UTC, zuhrasofyan commented
The star in the title will disappear once we remove it from the favorite, so I personally think the star color should be distinguished, but not the rest.

2024-05-29 10:14 UTC, zuhrasofyan commented
Fun fact: I am indeed literally partial color blind. So, this one is totally on me. I agree with your point and gladly will fix it 😄

2024-05-29 10:20 UTC, MrSerth commented
Ah, I didn't know, no worries.

Just to be sure: The star in the title is currently light grey, the folder icon is dark grey/black (similar to the title text). Is this what you mean with "the star color should be distinguished"?

2024-05-29 10:21 UTC, zuhrasofyan commented
Yes :)

2024-06-04 21:20 UTC, kkoehn approved these changes
Looks good to me now! Thanks for incorporating the feedback!

2024-06-04 22:21 UTC, merged