task import: handle errors during import better
openHPI/codeharbor pull request #1439
Opened 2024-06-04 19:59 UTC by kkoehn

2024-06-04 22:07 UTC, MrSerth requested changes
Nice, thank you! I really like the new error handling and think this will improve the fault tolerance. I have a few minor suggestions, but also one larger one regarding the current error handling: At least in my tests, I was able to generate another exception in the existing error handling (rescuing `ProformaXML::ProformaError`). I annotated two examples and hope that this will allow you to make the handling even more robust.

2024-06-04 22:07 UTC, MrSerth commented on config/locales/de/controllers/tasks.yml
> +      internal_error: Bei der Importierung der Aufgabe ist ein interner Fehler aufgetreten.
Just trying to improve the German wording a little; I know that you just moved it (due to the changed key):

```suggestion
      internal_error: Beim Import dieser Aufgabe ist auf CodeHarbor ein interner Fehler aufgetreten.
```

2024-06-04 22:07 UTC, MrSerth commented on config/locales/en/proforma_errors.yml
> +    version not supported: The version of this ProformaXML document is not supported
```suggestion
    version not supported: The version of this ProformaXML document is not supported.
```

2024-06-18 22:30 UTC, MrSerth approved these changes
Thanks! All errors I've tested were correctly handled and it looks nice. Thanks!

2024-06-18 22:30 UTC, MrSerth commented on config/locales/de/proforma_errors.yml
> +    version not supported: Die Version dieses ProformaXML Dokuments wird nicht unterstützt.
We recently aimed to unify the spelling to `ZIP-Datei`.

2024-06-18 22:30 UTC, MrSerth commented on config/locales/en/proforma_errors.yml
> +    version not supported: The version of this ProformaXML document is not supported.
In English, we use `ZIP file`.

2024-07-04 08:57 UTC, Dome-GER approved these changes
The `prettify_import_errors` looks a bit brittle. But I also don't have a much better idea right now.

2024-07-04 08:57 UTC, Dome-GER commented on config/locales/de/proforma_errors.yml
> +    import_default: "%{error}"
What is the benefit of this locale (in contrast to passing in the `msg` directly to the `default`)?

2024-07-04 08:57 UTC, Dome-GER commented on spec/controllers/tasks_controller_spec.rb
> +      it 'renders correct json' do
```suggestion
      it 'renders correct JSON' do
```

Nitpick. JSON is an acronym. But you probably use `json` everywhere.

2024-07-22 19:57 UTC, merged